name: "adguard"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    networks:
      - proxy

    volumes:
      - ${LAB_DIR}/config/adguard/workdir:/opt/adguardhome/work
      - ${LAB_DIR}/config/adguard/confdir:/opt/adguardhome/conf

    labels:
      - "glance.name=AdGuard Home"
      - "glance.icon=si:adguard"
      - "glance.url=https://adguard.${HOST_DOMAIN}"
      - "glance.description=Network-wide ad blocking"
      - "glance.category=infra"

      - "traefik.enable=${ADGUARD_TRAEFIK_ENABLED}"

      - "traefik.http.routers.adguard.rule=Host(`adguard.${HOST_DOMAIN}`)"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.tls=true"

      - "traefik.http.services.adguard.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
