name: "whoami"

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      # Router (domain -> service)
      - "traefik.http.routers.whoami.rule=Host(`whoami.${HOST_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"

      # Enable TLS via Let's Encrypt resolver
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

      # Middleware
      - "traefik.http.routers.whoami.middlewares=dashboard-auth@docker"
