name: "whoami"

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      # Router (domain -> service)
      - "traefik.http.routers.whoami.rule=Host(`whoami.${HOST_DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"

      # Middleware
      - "traefik.http.routers.whoami.middlewares=dashboard-auth@docker"


networks:
  proxy:
    external: true
    