services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    restart: unless-stopped

    ports:
      - "127.0.0.1:9000:9000"

    volumes:
      - ${LAB_DIR}/config/step-ca:/home/step/

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.step-ca.loadbalancer.server.port=9000"
      - "traefik.http.routers.step-ca.rule=Host(`step-ca.${HOST_DOMAIN}`)"
      - "traefik.http.routers.step-ca.entrypoints=websecure"
      - "traefik.http.services.step-ca.loadbalancer.server.scheme=https"
      - "traefik.http.routers.step-ca.tls.certresolver=stepca"

networks:
  proxy:
    external: true
