name: "traefik-prod"

services:
  traefik:
      ports:
        - "80:80"
        - "443:443"

      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ${LAB_DIR}/config/traefik/certs/:/certs:ro
        - ${LAB_DIR}/config/traefik/dynamic:/dynamic:ro
        - ${LAB_DIR}/config/traefik/letsencrypt:/letsencrypt

      command:
        # EntryPoints
        - "--entrypoints.web.address=:80"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
        - "--entrypoints.websecure.address=:443"

        # Let's Encrypt ACME
        - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
        - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
        - "--certificatesresolvers.myresolver.acme.email=${TRAEFIK_LETSENCRYPT_EMAIL}"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

        # API & Dashboard
        - "--api.dashboard=true"
        - "--api.insecure=false"

        # TLS
        - "--entrypoints.websecure.http.tls=true"

        # Providers
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.docker.network=proxy"

        # File provider for extra dynamic configs
        - "--providers.file.directory=/dynamic"
        - "--providers.file.watch=true"

        # Observability
        - "--log.level=INFO"
        - "--accesslog=true"
        - "--metrics.prometheus=false"

      labels:
        - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
