name: "traefik"

services:
  traefik:
    container_name: traefik
    image: traefik:v3.4
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    environment:
      - SSL_CERT_FILE=/etc/ssl/certs/root_ca.crt

    ports:
      - "80:80"
      - "443:443"

    networks:
      - proxy

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${LAB_DIR}/config/traefik/certs/:/certs:ro
      - ${LAB_DIR}/config/traefik/dynamic:/dynamic:ro
      - ${LAB_DIR}/config/traefik/letsencrypt:/letsencrypt
      - ${LAB_DIR}/config/step-ca/certs/root_ca.crt:/etc/ssl/certs/root_ca.crt:ro

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      # TLS
      - "--entrypoints.websecure.http.tls=true"

      # Local TLS
      - "--certificatesresolvers.stepca.acme.caServer=https://step-ca:9000/acme/acme/directory"
      - "--certificatesresolvers.stepca.acme.email=admin@example.com"
      - "--certificatesresolvers.stepca.acme.storage=/letsencrypt/acme-stepca.json"
      - "--certificatesresolvers.stepca.acme.tlschallenge=true"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"

      # File provider for extra dynamic configs
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"

      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"

      # Observability
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=false"

    labels:
      - "glance.name=Traefik"
      - "glance.icon=si:traefikproxy"
      - "glance.url=https://traefik.${HOST_DOMAIN}"
      - "glance.description=Reverse proxy"
      - "glance.category=infra"

      # Enable self-routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${HOST_DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic-auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_PASSWORD}"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

networks:
  proxy:
    name: proxy
