pages:
  - name: Startpage
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: docker-containers
            title: 'Infra'
            category: infra

          - type: server-stats
            servers:
              - type: local
                name: Services
